### ISSUE TITLE
Enhancement Issue: Looking for Alternatives to win32api to get drive letters.

### ISSUE THREAD

**Issue by Anish-M-code** [nuras1999/simple-textfile-worm#2]
I think it would be better to use native python standard libraries compared to thirdparty modules like
win32api. Reference : https://stackoverflow.com/questions/827371/is-there-a-way-to-list-all-the-available-drive-letters-in-python

**Comment by Anish-M-code** [comment]
I felt it would help less technical users to use the python code as they would be more interested to
just copy and paste code and third party modules might be a pain for them.

**Comment by nuras1999** [comment]
True. That is a good idea. Implementing these ideas would be better. Thanks
